#! /bin/sh

bspc monitor 					-d	1 2 3 4 5
bspc config border_width 			4
bspc config window_gap				10
bspc config split_ratio				0.5
bspc config single_monocle			falce
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"#282A36"
bspc config active_border_color		"#8BE9FD"
bspc config presel_feedback_color	"#50FA7B"

dunst &
sxhkd &
xsetroot -cursor_name left_ptr
xset r rate 200 50

# Kill old bars
killall -q polybar

# Launch bar
polybar mainbar &
picom &
